
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URI: http://localhost:5000
    
    ports:
      - "3000:80"

    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      HOST: database

    depends_on:
      - database

  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7ttfhnY@
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
